// Single source of truth for the RX form's option lists, shared by the form,
// the Convex validation schema and the email templates. Appliance names and
// grouping follow the paper RX form (public/rx-form.pdf).

export const OTHER_APPLIANCE = 'Other - Specify Below';

export const applianceGroups = [
  {
    label: 'Orthodontic & Pediatric Appliances',
    items: [
      'Hawley Retainer U/L',
      'Hawley Retainer U/L 2x2 Wire',
      'Dugoni Retainer',
      'Wraparound Retainer',
      'Modified Spring Retainer',
      'Schwarz',
      'Nance Holding Arch',
      'Quad Helix Expansion "W" Arch',
      'Hyrax Rapid Palatal Expander',
      'Haas Palatal Separator',
      'Bonded R.P.E.',
      'Habit Crib',
      '6x6 Lingual Arch',
      'Space Maintainer',
    ],
  },
  {
    label: 'Splint / T.M.J. Appliances',
    items: ['Horseshoe Splint (Bruxism)', 'Gelb/Mora', 'Invisible Retainer/Essex'],
  },
  {
    label: 'Other',
    items: [OTHER_APPLIANCE],
  },
] as const;

export const appliances = applianceGroups.flatMap((g) => g.items);

// Shown to the doctor as "Arch"; the stored `position` key predates the rename.
export const positions = ['Upper', 'Lower', 'Both'] as const;

export const clasps = ['Adams Clasp', 'Ball Clasp', 'C Clasp', 'Other - Specify Below'] as const;

// The form defaults to NO_SPRING. A spring's details go in the additional information.
export const NO_SPRING = 'No Spring';
export const springs = [NO_SPRING, 'Spring - Specify Below'] as const;

export const colors = [
  'Any',
  'Wine',
  'Black Cherry',
  'Fluorescent Pink',
  'Raspberry',
  'Cranberry',
  'Cherry',
  'Root Beer Brown',
  'Persimmon',
  'Tangerine',
  'Gold',
  'Amber',
  'Lemon Yellow',
  'Fluorescent Yellow',
  'Apple Green',
  'Grass Green',
  'Emerald Green',
  'Teal Green',
  'Aqua Blue',
  'Turquoise',
  'Caribbean Blue',
  'Ice Blue',
  'Special Med Blue',
  'Sapphire Blue',
  'Cobalt Blue',
  'Light Purple',
  'Purple',
  'Light Violet',
  'Violet',
  'Black Onyx Liquid',
  'Crystal Clear',
  'Standard Pink',
  'Tinted Clear',
  'Luminary Red',
  'Luminary Pink',
  'Luminary Coral Red',
  'Luminary Orange',
  'Luminary Blaze Yellow',
  'Luminary Yellow',
  'Luminary Green',
  'Luminary Teal Green',
  'Luminary Blue',
  'Luminary Blueberry',
  'Luminary Purple',
  'Luminary Chartreuse',
  'Royal Red',
  'Royal Pink',
  'Royal Coral Red',
  'Royal Orange',
  'Royal Blaze Yellow',
  'Royal Yellow',
  'Royal Green',
  'Royal Teal Green',
  'Royal Blue',
  'Royal Blueberry',
  'Royal Purple',
  'Crimson Red',
  'Candy Apple Red',
  'Cameo Pink',
  'Sunrise Orange',
  'Mustard Yellow',
  'Banana Yellow',
  'Shamrock Green',
  'Fern Green',
  'Watermelon Green',
  'Sky Blue',
  'Baby Blue',
  'Lapis Blue',
  'Nautical Blue',
  'Amethyst',
  'Dove Gray',
  'Dolphin Gray',
  'Black Opaque',
  'White Opaque',
  'Caramel Tan',
  'Chocolate Brown',
  'Pink Pearl',
  'Peach Pearl',
  'Yellow Pearl',
  'Green Pearl',
  'Aqua Pearl',
  'Blue Pearl',
  'Lavender Pearl',
  'Lilac Pearl',
  'Pearl White',
  'Midnight Black',
  'Opalescent Sparkle',
  'Silver Sparkle',
  'Red Sparkle',
  'Golden Orange',
  'Copper Sparkle',
  'Salmon Pink',
  'Aztec Gold',
  'Kiwi Sparkle',
  'Green Sparkle',
  'Hunter Green',
  'Aqua Sparkle',
  'Crystal Blue',
  'Turquoise Sparkle',
  'Blue Sparkle',
  'Purple Sparkle',
  'Lavender',
  'Fuchsia',
  'Black Sparkle',
  'Red Hatter',
  'Tutti Frutti',
  'Carnival Blue',
  'Miss Priss',
  'Peacock',
  'Pastel Rainbow',
  'Disco Rainbow',
  'USA Sparkle',
] as const;
